services:
  pear:
    build:
      context: .
      args:
        PEAR_CACHEBUST: ${PEAR_CACHEBUST:-1}
    image: pear:latest
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
